# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jun - S/W Engineer
title: Junseok Oh
email: ohjunseok842@gmail.com
description: >- 
    
baseurl: ""
url: "http://junsoh.com"
github_username: batt842
linkedin_username: junseok-oh-91885882
facebook_username: junseok.oh.39
instagram_username: jun.s.oh

# Build settings
markdown: kramdown # Quick Reference : https://kramdown.gettalong.org/quickref.html
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - posts.md
  - aboutme.md

google_analytics: UA-127047509-1

disqus:
  shortname: junsoh

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
